DROP TABLE `languages`;
CREATE TABLE IF NOT EXISTS `languages` (
  `code` varchar(12) character set utf8 collate utf8_unicode_ci NOT NULL,
  `description` varchar(32) character set utf8 collate utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `languages` (`code`, `description`) VALUES
('abap', 'ABAP'),
('actionscript', 'ActionScript'),
('actionscript3', 'ActionScript 3'),
('ada', 'Ada'),
('algol68', 'ALGOL 68'),
('apache', 'Apache configuration'),
('applescript', 'AppleScript'),
('apt_sources', 'Apt sources'),
('asm', 'ASM'),
('asp', 'ASP'),
('autoconf', 'Autoconf'),
('autohotkey', 'Autohotkey'),
('autoit', 'AutoIt'),
('avisynth', 'AviSynth'),
('awk', 'awk'),
('bascomavr', 'BASCOM AVR'),
('bash', 'Bash'),
('basic4gl', 'Basic4GL'),
('bf', 'Brainfuck'),
('bibtex', 'BibTeX'),
('blitzbasic', 'BlitzBasic'),
('bnf', 'bnf'),
('boo', 'Boo'),
('caddcl', 'CAD DCL'),
('cadlisp', 'CAD Lisp'),
('cfdg', 'CFDG'),
('cfm', 'ColdFusion'),
('cil', 'CIL'),
('c_loadrunner', 'C (LoadRunner)'),
('clojure', 'Clojure'),
('c_mac', 'C (Mac)'),
('cmake', 'CMake'),
('cobol', 'COBOL'),
('coffeescript', 'CoffeeScript'),
('c', 'C'),
('cpp', 'C++'),
('cpp-qt', 'C++ (QT)'),
('csharp', 'C#'),
('css', 'CSS'),
('cuesheet', 'Cuesheet'),
('dcs', 'DCS'),
('delphi', 'Delphi'),
('diff', 'Diff'),
('div', 'DIV'),
('dos', 'DOS'),
('dot', 'dot'),
('d', 'D'),
('ecmascript', 'ECMAScript'),
('eiffel', 'Eiffel'),
('email', 'eMail (mbox)'),
('epc', 'EPC'),
('e', 'E'),
('erlang', 'Erlang'),
('euphoria', 'Euphoria'),
('falcon', 'Falcon'),
('fo', 'FO (abas-ERP)'),
('fortran', 'Fortran'),
('freebasic', 'FreeBasic'),
('fsharp', 'F#'),
('f1', 'Formula One'),
('gambas', 'GAMBAS'),
('gdb', 'GDB'),
('genero', 'genero'),
('genie', 'Genie'),
('gettext', 'GNU Gettext'),
('glsl', 'glSlang'),
('gml', 'GML'),
('gnuplot', 'Gnuplot'),
('go', 'Go'),
('groovy', 'Groovy'),
('gwbasic', 'GwBasic'),
('haskell', 'Haskell'),
('hicest', 'HicEst'),
('hq9plus', 'HQ9+'),
('html4strict', 'HTML'),
('html5', 'HTML'),
('chaiscript', 'ChaiScript'),
('icon', 'Icon'),
('idl', 'Uno Idl'),
('ini', 'INI'),
('inno', 'Inno'),
('intercal', 'INTERCAL'),
('io', 'Io'),
('java', 'Java'),
('javascript', 'Javascript'),
('java5', 'Java(TM) 2 Platform Standard Edition 5.0'),
('j', 'J'),
('jquery', 'jQuery'),
('kixtart', 'KiXtart'),
('klonec', 'KLone C'),
('klonecpp', 'KLone C++'),
('latex', 'LaTeX'),
('lb', 'Liberty BASIC'),
('lisp', 'Lisp'),
('llvm', 'LLVM Intermediate Representation'),
('locobasic', 'Locomotive Basic'),
('logtalk', 'Logtalk'),
('lolcode', 'LOLcode'),
('lotusformulas', 'Lotus Notes @Formulas'),
('lotusscript', 'LotusScript'),
('lscript', 'LScript'),
('lsl2', 'LSL2'),
('lua', 'Lua'),
('magiksf', 'MagikSF'),
('make', 'GNU make'),
('mapbasic', 'MapBasic'),
('matlab', 'Matlab M'),
('mirc', 'mIRC Scripting'),
('mmix', 'MMIX'),
('modula2', 'Modula-2'),
('modula3', 'Modula-3'),
('mpasm', 'Microchip Assembler'),
('mxml', 'MXML'),
('mysql', 'MySQL'),
('m68k', 'Motorola 68000 Assembler'),
('newlisp', 'newlisp'),
('nsis', 'NSIS'),
('oberon2', 'Oberon-2'),
('objc', 'Objective-C'),
('objeck', 'Objeck Programming Language'),
('ocaml-brief', 'OCaml (brief)'),
('ocaml', 'OCaml'),
('oobas', 'OpenOffice.org Basic'),
('oracle11', 'Oracle 11 SQL'),
('oracle8', 'Oracle 8 SQL'),
('oxygene', 'Oxygene (Delphi Prism)'),
('oz', 'OZ'),
('pascal', 'Pascal'),
('pcre', 'PCRE'),
('perl', 'Perl'),
('perl6', 'Perl 6'),
('per', 'per'),
('pf', 'OpenBSD Packet Filter'),
('php-brief', 'PHP (brief)'),
('php', 'PHP'),
('pic16', 'PIC16'),
('pike', 'Pike'),
('pixelbender', 'Pixel Bender 1.0'),
('pli', 'PL/I'),
('plsql', 'PL/SQL'),
('postgresql', 'PostgreSQL'),
('povray', 'POVRAY'),
('powerbuilder', 'PowerBuilder'),
('powershell', 'PowerShell'),
('proftpd', 'ProFTPd configuration'),
('progress', 'Progress'),
('prolog', 'Prolog'),
('properties', 'PROPERTIES'),
('providex', 'ProvideX'),
('purebasic', 'PureBasic'),
('python', 'Python'),
('qbasic', 'QBasic/QuickBASIC'),
('q', 'q/kdb+'),
('rails', 'Rails'),
('rebol', 'REBOL'),
('reg', 'Microsoft Registry'),
('robots', 'robots.txt'),
('rpmspec', 'RPM Specification File'),
('rsplus', 'R / S+'),
('ruby', 'Ruby'),
('sas', 'SAS'),
('scala', 'Scala'),
('scilab', 'SciLab'),
('sdlbasic', 'sdlBasic'),
('scheme', 'Scheme'),
('smalltalk', 'Smalltalk'),
('smarty', 'Smarty'),
('sql', 'SQL'),
('systemverilog', 'SystemVerilog'),
('tcl', 'TCL'),
('teraterm', 'Tera Term Macro'),
('text', 'Text'),
('thinbasic', 'thinBasic'),
('tsql', 'T-SQL'),
('typoscript', 'TypoScript'),
('unicon', 'Unicon (Unified Extended Dialect of Icon)'),
('uscript', 'Unreal Script'),
('vala', 'Vala'),
('vbnet', 'vb.net'),
('vb', 'Visual Basic'),
('verilog', 'Verilog'),
('vhdl', 'VHDL'),
('vim', 'Vim Script'),
('visualfoxpro', 'Visual Fox Pro'),
('visualprolog', 'Visual Prolog'),
('whitespace', 'Whitespace'),
('whois', 'Whois (RPSL format)'),
('winbatch', 'Winbatch'),
('xbasic', 'XBasic'),
('xml', 'XML'),
('xorg_conf', 'Xorg configuration'),
('xpp', 'X++'),
('yaml', 'YAML'),
('zxbasic', 'ZXBasic'),
('z80', 'ZiLOG Z80 Assembler'),
('4cs', 'GADV 4CS'),
('6502acme', 'MOS 6502 (6510) ACME Cross Assembler format'),
('6502kickass', 'MOS 6502 (6510) Kick Assembler format'),
('6502tasm', 'MOS 6502 (6510) TASM/64TASS 1.46 Assembler format'),
('68000devpac', 'Motorola 68000 - HiSoft Devpac ST 2 Assembler format'),
('image', 'Image file');
